;[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]
;           Common Styles 
;[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]

[sText]
FontFace=#NewsFont#
FontSize=9
StringStyle=BOLD
StringAlign=LEFT
StringEffect=SHADOW
AntiAlias=1

[sColorSet1]
FontColor=2f1d0c
FontEffectColor=ccbdae88

[sColorSet2]
FontColor=201203
FontEffectColor=aeaeae



