[Variables]

; It is unlikely that you will change this.
Interface=Best

; It is IMPORTANT that these be set for your network's maximum supported download and upload speeds, in order for the Bar meters to be accurate. 
; See the thread at http://rainmeter.net/forum/viewtopic.php?f=15&t=16402 for details on this.
; The long and the short of it is that you need to go to http://speedtest.net, run the test,
; and plug in the Download and Upload numbers it provides in the variables below.
MaxDownloadMb=49.00
MaxUploadMb=7.00

; Change this to show (1) or not (0) the WIFI panel when you mouse over the skin.
ShowWIFI=1

; General skin variables.
; Don't change these.
NetOffSet=0
WIFIOffSet=170
NetAlpha=255
WIFIAlpha=0